// <auto-generated />
using System;
using BackendInsurance.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackendInsurance.Migrations
{
    [DbContext(typeof(InsuranceContext))]
    [Migration("20260129042708_InitDatabase")]
    partial class InitDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BackendInsurance.Models.Poliza", b =>
                {
                    b.Property<int>("PolizaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PolizaID"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Contry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherLastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MontoPrima")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MotherLastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Names")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroPoliza")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phonenumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoPolizaID")
                        .HasColumnType("int");

                    b.HasKey("PolizaID");

                    b.HasIndex("TipoPolizaID");

                    b.ToTable("Polizas");
                });

            modelBuilder.Entity("BackendInsurance.Models.Role", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleID"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleID");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleID = 1,
                            name = "Admin"
                        },
                        new
                        {
                            RoleID = 2,
                            name = "Broker"
                        },
                        new
                        {
                            RoleID = 3,
                            name = "Cliente"
                        });
                });

            modelBuilder.Entity("BackendInsurance.Models.TipoPoliza", b =>
                {
                    b.Property<int>("TipoPolizaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoPolizaID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TipoPolizaID");

                    b.ToTable("TipoPolizas");

                    b.HasData(
                        new
                        {
                            TipoPolizaID = 1,
                            Name = "Hogar"
                        },
                        new
                        {
                            TipoPolizaID = 2,
                            Name = "Vida"
                        },
                        new
                        {
                            TipoPolizaID = 3,
                            Name = "Auto"
                        },
                        new
                        {
                            TipoPolizaID = 4,
                            Name = "Salud"
                        });
                });

            modelBuilder.Entity("BackendInsurance.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.HasIndex("RoleID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            RoleID = 1,
                            email = "admin@gmail.com",
                            password = "123456789",
                            username = "admin"
                        });
                });

            modelBuilder.Entity("BackendInsurance.Models.Poliza", b =>
                {
                    b.HasOne("BackendInsurance.Models.TipoPoliza", "TipoPoliza")
                        .WithMany()
                        .HasForeignKey("TipoPolizaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoPoliza");
                });

            modelBuilder.Entity("BackendInsurance.Models.User", b =>
                {
                    b.HasOne("BackendInsurance.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });
#pragma warning restore 612, 618
        }
    }
}
